site_name: My GitHub Pages
site_url: https://rosseboe.github.io/
theme:
  name: material
 
  features:
    - content.code.copy

nav:
  - Home: index.md
  - PID Simulator: pid_simulator.md
  - Arduino: arduino.md
  - Git: git.md
  - IIA1319: IIA1319.md
  - IIA3220: IIA3220.md
  - Tips: tips.md

markdown_extensions:
  - attr_list
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
